config/routes.rb
Boba::Application.routes.draw do
  resources :comments

  get "pages/info"
  root :to => redirect('/tapiocas')
  resources :tapiocas

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/tapioca.rb
class Tapioca < ActiveRecord::Base
	has_many :comments
	mount_uploader :picture, PictureUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :tapioca_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/tapiocas_controller.rb
class TapiocasController < ApplicationController
  before_action :set_tapioca, only: [:show, :edit, :update, :destroy]

  # GET /tapiocas
  # GET /tapiocas.json
  def index
    @tapiocas = Tapioca.all
    @hash = Gmaps4rails.build_markers(@tapiocas) do |tapioca, marker|
      marker.lat tapioca.latitude
      marker.lng tapioca.longitude
    end
  end

  # GET /tapiocas/1
  # GET /tapiocas/1.json
  def show
  end

  # GET /tapiocas/new
  def new
    @tapioca = Tapioca.new
  end

  # GET /tapiocas/1/edit
  def edit
  end

  # POST /tapiocas
  # POST /tapiocas.json
  def create
    @tapioca = Tapioca.new(tapioca_params)

    respond_to do |format|
      if @tapioca.save
        format.html { redirect_to @tapioca, notice: 'Tapioca was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tapioca }
      else
        format.html { render action: 'new' }
        format.json { render json: @tapioca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tapiocas/1
  # PATCH/PUT /tapiocas/1.json
  def update
    respond_to do |format|
      if @tapioca.update(tapioca_params)
        format.html { redirect_to @tapioca, notice: 'Tapioca was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tapioca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tapiocas/1
  # DELETE /tapiocas/1.json
  def destroy
    @tapioca.destroy
    respond_to do |format|
      format.html { redirect_to tapiocas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tapioca
      @tapioca = Tapioca.find(params[:id])
      @comment = @tapioca.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tapioca_params
      params.require(:tapioca).permit(:name, :description, :picture)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tapiocas_helper.rb
module TapiocasHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tapioca_id %><br>
    <%= f.number_field :tapioca_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Tapioca</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.tapioca_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Tapioca:</strong>
  <%= @comment.tapioca_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boba</title>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">WTB?! Where's the boba?!</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
         <li><a href="/tapiocas">Home</a></li> <!-- class="active"-->
         <li><%= link_to 'Add a Drink', new_tapioca_path %></li>
         <li><a href="/pages/info">About This Site</a></li>
       </ul>
     </div>
   </div>
 </nav>

 <div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Rails Girls 2013
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/tapiocas/_form.html.erb
<%= form_for(@tapioca) do |f| %>
  <% if @tapioca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tapioca.errors.count, "error") %> prohibited this tapioca from being saved:</h2>

      <ul>
      <% @tapioca.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_area :latitude %>
  </div>
     <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_area :longitude %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tapiocas/edit.html.erb
<h1>Editing tapioca</h1>

<%= render 'form' %>

<%= link_to 'Show', @tapioca %> |
<%= link_to 'Back', tapiocas_path %>

app/views/tapiocas/index.html.erb
<h1>Listing Bobas</h1>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>


<script type="text/javascript">
$(function(){
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers([
		{
			"lat": 0,
			"lng": 0,
			"picture": {
				"url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
				"width":  36,
				"height": 36
			},
			"infowindow": "hello!"
		}
		]);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
	});
	console.log(<%= raw @hash.to_json%>)
	markers = handler.addMarkers(<%=raw @hash.to_json %>);
})
</script>

<% @tapiocas.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |tapioca| %>
      <div class="span4">
        <%= image_tag tapioca.picture_url, :width => '100%' if tapioca.picture.present?%>
        <h4><%= link_to tapioca.name, tapioca %></h4>
        <%= tapioca.description %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tapiocas/new.html.erb
<h1>New tapioca</h1>

<%= render 'form' %>

<%= link_to 'Back', tapiocas_path %>

app/views/tapiocas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span9">
    <%= image_tag(@tapioca.picture_url, :width => "100%") if @tapioca.picture.present? %>
    <h3>Comments</h3>
<% @tapioca.comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %></p>
  </div>
<% end %>
<%= render 'comments/form' %>
  </div>

  <div class="span3">
    <p><b>Name: </b><%= @tapioca.name %></p>
    <p><b>Description: </b><%= @tapioca.description %></p>
    <p>
      <%= link_to 'Edit', edit_tapioca_path(@tapioca) %> |
      <%= link_to 'Destroy', @tapioca, confirm: 'Are you sure?', method: :delete %> |
      <%= link_to 'Back', tapiocas_path %>
    </p>
  </div>
</div>